# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79e541556db3c29b27781263f09bb769425a0faf7657a2f43a873c2f0c9ad9b8954a37a469eb278cc20a9c64f0ec9c4e834c645e41543f96e69b78033a6fea30

test:
  secret_key_base: fc224493214ddac8a4601853352baf356403259b3041b6c9d578d5e9309e01ef480dff617d52712b3e1271b5198b94739c58555b553f9d72369ab8bc8f0ef876

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
